---
- name: copying repo helm
  become: true
  copy:
    src: ../../../../helm
    dest: /home/cp/
    owner: 1000 
    group: 1000
    mode: 0644
- name: Install Chart
  kubernetes.core.helm:
    name: repo
    chart_ref: /home/cp/helm/app
    release_namespace: kiratech-test
    create_namespace: true
     #@- name: install helm
#  roles:
#  - role: gantsign.helm
